### ISSUE TITLE
Image import

### ISSUE THREAD

**Issue by Arrappathor** [circuscode/mathilda#2]
Hi, it's me again.
If my tweet contains two (or more?) images, Mathilda only imports the first one and therefore only displays this one image on the blog-tweet. The second (and further ones?) is (are) ignored.
Is this correct and if so, is there a workaround (without coding-skills) to show/have more images? 
OS was Raspbian Stretch with MariaDB.
Anyway, fine tool!
Thanks
tg

**Comment by circuscode** [comment]
Hey!
Thank you very much for reporting this. The plugin does support galleries. Maybe this is again an issue with MariaDB. Or this feature gets broken by something. I do not use galleries often. Give me some time, I will look into this error. Hopefully coming back with a solution.
Best Regards
Marco

**Comment by circuscode** [comment]
Hey.
I was wrong. I have never implemented this feature. ;-)
But now it is and tweet galleries are supported. 
Could you run a short test and confirm me, if it works?
Just replace the current plugin files with the files from this repository. After that you just have to tweet a gallery and run the load. Previous will not be activated automaticly. For this, it is required to reset mathilda and reload/import all tweets again.
If the new feature works, it would release it in the wordpress repository.
Best Regards
Marco

**Comment by Arrappathor** [comment]
Hey, 
as I had no gallery to tweet at the moment, I just resetted and re-ran Mathilda after updating from the new repository. Et voilà: two images. I assume new gallery-tweets will also be correctly dislayed.
Thank you very much for your immediate efforts and: for implementing the new feature.
Very cool!
tg

**Comment by circuscode** [comment]
Thanks for your response. I will release the new version in the plugin repository in a few moments. Please take all files from this repository again und copy it over the existing. I have added a further bugfix and I assume you do not get it automaticly via the wordpress update, because of installation of the prerelease.
