### ISSUE TITLE
Import from Twitter

### ISSUE THREAD

**Issue by Arrappathor** [circuscode/mathilda#6]
Hello, it's me again.
I had to reset my mathilda. When i wanted to re-import my tweets from twitter, i found that the format of its archives has  changed: the folder /data/js/tweets has gone and is replaced by various media_folders and .js-files:
![twitter_data](https://user-images.githubusercontent.com/17974573/95813164-8e6f4d80-0d17-11eb-8f0e-8656bf599324.png)
What files need to be uploaded now? May i just take the tweets.js (which seems to contain all the tweets and links)?
Thank you very much!

**Comment by circuscode** [comment]
Hey Arrappathor.
Thank you for reporting of this issue. I was not aware that the twitter has changed the structure of its archive. I will look into it. Just waiting for the download of my tweet data.
Best Regards
Marco

**Comment by circuscode** [comment]
Bad news. Twitter has changed the data structure of the export. So the current import procedure of the plugin cannot process the data anymore. But this is not the large problem. This could be solved with adjustments of the algorithm. But the real problem is, with the new export, all tweets are bundled in 1 file (tweets.js). So the file size is several megabytes, which cannot be progressed by PHP in a web environment. The runtime of a PHP program is normally limited to 30 seconds, which is not enough for the plugin. I must think about what could be a possible solutions. This will take time.

**Comment by Arrappathor** [comment]
Ok, thanks for your quick response!

**Comment by circuscode** [comment]
Hey! 
I have good news and bad news.
The good:
I have reworked the import routine. It's now compatible with the new DSGVO data export from twitter. You can download the new routine from the following link. Just copy the file into the plugin folder.
[mathilda_import.php](https://github.com/circuscode/mathilda/blob/feature/twitter-dsgvo-export/mathilda_import.php)
Please be aware, this is a pre-release file. I had to made some additional changes before it can be shipped with the next release.
The bad:
You have to do some prework before it will work. The tweet data is now stored in the tweet.js file as you have already found out. This file is to big for the progressing via PHP. It must be splitted into smaller files manually. The smaller files should have around 300KB. For this you can use a terminal script like the following.
[JSON SPLITTER](https://github.com/jhsu98/json-splitter)
In the first moments is sounds complex. But on MacOS Catalina (for example) it's relatively simple. But you can also use other tools for sure. Before you start, please remove the first string until "[" in the file tweet.js.
Best Regards
Marco

**Comment by Arrappathor** [comment]
Hey Marco
thank you very much!
My tweets.js-file is no that big (< 1MB, ~270 tweets) so i didn't have to split it.
But Twitter seems to have reduced the number of tweets to load to 200; so i missed my last 70.
Anyway, it worked out, you worked it out! Thank you very much, it's such a fine tool!
Will there be an official plugin-update and will i be informed via wordpress-dashboard?
Best regards!
Arrappathor

**Comment by circuscode** [comment]
Yes, you will get the official plugin update on the usual way.
Regarding the mentioned gap. You should not miss any tweets. The import file contains all tweets. If you import this you have all in. The regular load will copy then only the latest tweets, which are not included in the import file. This also works the other way around. First load your latest 200 tweets. After that you can import the gap of 70 tweets via file.
Best Regards
Marco

**Comment by circuscode** [comment]
Feature is included in Release 0.11, which will be shipped in a few moments.
